// Code generated by "stringer -type=MsgType"; DO NOT EDIT.

package peer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MsgChoke-0]
	_ = x[MsgUnchoke-1]
	_ = x[MsgInterested-2]
	_ = x[MsgNotInterested-3]
	_ = x[MsgHave-4]
	_ = x[MsgBitfield-5]
	_ = x[MsgRequest-6]
	_ = x[MsgPiece-7]
	_ = x[MsgCancel-8]
	_ = x[MsgExtended-20]
}

const (
	_MsgType_name_0 = "MsgChokeMsgUnchokeMsgInterestedMsgNotInterestedMsgHaveMsgBitfieldMsgRequestMsgPieceMsgCancel"
	_MsgType_name_1 = "MsgExtended"
)

var (
	_MsgType_index_0 = [...]uint8{0, 8, 18, 31, 47, 54, 65, 75, 83, 92}
)

func (i MsgType) String() string {
	switch {
	case i <= 8:
		return _MsgType_name_0[_MsgType_index_0[i]:_MsgType_index_0[i+1]]
	case i == 20:
		return _MsgType_name_1
	default:
		return "MsgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
